### PR TITLE
Update python.cson

### PR DESCRIPTION
**Pull request by UltraHR**
language-renpy now deals with .rpy files.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Keeping it here allows them to still be highlighted when `language-renpy` is not installed.

Is having the `.rpy` extension here causing issues?

**Comment by UltraHR** [comment]
But when language-renpy is installed it still takes the .rpy extensions, which is not convenient. .rpy is not a common extension for python files anyway, so .rpy should be given soley to language-renpy.

**Comment by 50Wliu** [comment]
@UltraHR community packages now take precedence in the latest (at least 0.201.0) version of Atom.

**Comment by kevinsawicki** [comment]
Closing this since it should be fixed by as mentioned by @50Wliu

**Pull request closed without merging**
