### PR TITLE
Add support to highlight function names

### PR DESCRIPTION
**Pull request by ElDeveloper**
With this snippet function names will be highlighted in a different
color, note that this does not refer to the function definition i. e.
`def foo()` but instead to a piece of code that calls `foo()`.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Hey @ElDeveloper, sorry for the really long lag in reviewing this.  Can you please add specs for your changes?  Thanks.

**Comment by thedaniel** [comment]
This appears to be abandoned - I've added the `help-wanted` label in case anyone else in the community wants to pick this up and add some specs.

**Comment by hrvoojex** [comment]
Is there a way to highlight Python function calls in Atom 1.18?

**Comment by ElDeveloper** [comment]
Just ran into this. @thedaniel would you mind explaining what specs are needed? I'll try to put them in place.

**Comment by thedaniel** [comment]
Sorry, I'm not involved in this project any more and I'm not sure who you should mention directly. Hopefully a maintainer sees this activity and provides a response!

**Comment by rsese** [comment]
:wave: @ElDeveloper - as you may have heard, we're migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we've decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available as there is for language-python. 

Can you confirm if this is still an issue with Tree-sitter enabled (Tree-sitter is enabled by default in the latest releases but you can also check at `Settings > Core > Enable Tree Sitter Parsers`)?  Just want to make sure I'm on the same page based on your screenshots in  https://github.com/atom/language-python/pull/10#issuecomment-41966984.

**Comment by ElDeveloper** [comment]
@rsese you are right, this is no longer an issue and this PR is no longer needed.

**Comment by rsese** [comment]
Thanks for confirming @ElDeveloper :bow:

**Pull request closed without merging**
