### PR TITLE
Support return value annotations in functions

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds support for return value annotations in functions (as requested in #68) and fixes an error reported in #86.

``` python
def init(self, int = 3) -> None :
        """Construct semantic analyzer.
        """
        self.pyversion = pyversion

def visit_file(self, file_node: MypyFile, fnam: str) -> None:
        self.errors.set_file(fnam)
        self.errors.set_ignored_lines(file_node.ignored_lines)
        self.cur_mod_node = file_node
```

See the [fix in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-python%2F02d464d2bd5d6185d0af4c5db7e2467dbdcad5c6%2Fgrammars%2Fpython.cson&grammar_text=&code_source=from-text&code_url=&code=def+init%28self%2C+int+%3D+3%29+-%3E+None+%3A%0D%0A++++++++%22%22%22Construct+semantic+analyzer.%0D%0A++++++++%22%22%22%0D%0A++++++++self.pyversion+%3D+pyversion%0D%0A%0D%0Adef+visit_file%28self%2C+file_node%3A+MypyFile%2C+fnam%3A+str%29+-%3E+None%3A%0D%0A++++++++self.errors.set_file%28fnam%29%0D%0A++++++++self.errors.set_ignored_lines%28file_node.ignored_lines%29%0D%0A++++++++self.cur_mod_node+%3D+file_node).

It loses the `invalid.illegal` scope for function headers without a terminating `:`. I couldn't find a way to keep it. Though, most of the time, [you can still clearly see that it's missing](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-python%2F02d464d2bd5d6185d0af4c5db7e2467dbdcad5c6%2Fgrammars%2Fpython.cson&grammar_text=&code_source=from-text&code_url=&code=def+init%28self%2C+int+%3D+3%29+-%3E+None%0D%0A++++++++%22%22%22Construct+semantic+analyzer.%0D%0A++++++++%22%22%22%0D%0A++++++++self.pyversion+%3D+pyversion%0D%0A%0D%0Adef+visit_file%28self%2C+file_node%3A+MypyFile%2C+fnam%3A+str%29+-%3E+None%3A%0D%0A++++++++self.errors.set_file%28fnam%29%0D%0A++++++++self.errors.set_ignored_lines%28file_node.ignored_lines%29%0D%0A++++++++self.cur_mod_node+%3D+file_node).

### CODE REVIEW

**Comment by berdario** [comment]
re: Isn't #95 the same as this one? 

I'm not quite sure about your changes (otoh, I haven't tried to run them yet... but I don't know how to do it, either... I know only how to run tests, and this PR doesn't make any change to tests): you removed stuff from the regexps, so I'm a bit confused as how this could actually parse correctly the `->` token needed for function annotations

Is the test that I wrote in #95 potentially useful to be reused?
Anyhow, the scope for that other PR was to handle all function annotations, not only return value annotations

Good to know that you're working on it :)

**Comment by pchaigno** [comment]
> re: Isn't #95 the same as this one? 

But mine's older :stuck_out_tongue_winking_eye: 

> Is the test that I wrote in #95 potentially useful to be reused?
Anyhow, the scope for that other PR was to handle all function annotations, not only return value annotations

I'll try to take a look at this over the week-end (I'll add on your PR if it's more complete than mine ;).

**Comment by berdario** [comment]
Sure

Since you seem to be more knowledgeable about this project than me:

Do you have any pointers/documentation? The README is pretty laconic

**Comment by pwaller** [comment]
@pchaigno any chance of getting this in? The highlighting is completely broken to the point of distraction for code with return annotations at the moment.

**Comment by berdario** [comment]
@pwaller
Just install MagicPython

https://github.com/MagicStack/MagicPython

See also

https://github.com/atom/language-python/issues/109

**Pull request closed without merging**
